- plugins/restful/datatag_handle.c
1. Fix add tags handler error handling
2. Fix del tags handler error handling
> Fix restful tag handler error handling

- plugins/mqtt/command/datatag.c
1. Fix mqtt plugin add tags command handler error handling
2. Fix mqtt plugin del tags command handler error handling
> Fix mqtt plugin tags command error handling

- src/persist/persist.c
This will fix the persistence data file structure to be fully compilant with [nep](https://github.com/neugates/nep/pull/21/files)
> Fix persistence data file structure according to nep

- plugins/mqtt/command/read_write.c
> Fix mqtt write return value type error

- src/persist/persist.c
1. Refactor persistence api function neu_persister_store_subscriptions
2. Refactor persistence api function neu_persister_load_subscriptions
> Refactor subscriptoin persistence api functions 

- include/neu_log.h
- src/main.c
- src/utils/log.c
1. Rename neu_log log level enum to avoid name collision
2. Add syslog callback in neu_log
> Add syslog support

- src/adapter/adapter.c
- src/core/neu_manager.c
- src/core/neu_manager.h
1. Add function neu_manager_get_node_id_by_name
2. Add function neu_manager_adapter_get_grp_config_ref_by_name
3. Add function persister_singleton_load_subscriptions
4. Update persist adapter to load subscription infos
> Add feature for loading subscription infos from persistence data

- .github/workflows/dev.yml
- ft/Keyword/Neuron.py
- ft/pressure.test
- ft/requirements.txt
1. Add dependencies for pressure testing
2. Add robot keyword Profile Neuron for pressure testing report
3. Profile CPU and MEM usage in pressure testing
4. Fix CI for pressure testing
> Make pressure testing report CPU and MEM usage

- ft/common.resource
- ft/data/persistence/simple-10k/adapters.json
- ft/data/persistence/simple-1k/adapters.json
- ft/data/persistence/total-1k/adapters.json
- ft/data/persistence/total-50k/adapters.json
- ft/pressure.test
1. Fix pressure testing persistence data
2. Fix robot keyword Copy Persistence Test Data
3. Ignore sample app/driver adapter in pressure testing read/write loop
4. Fix pressure testing read/write loop
> Fix pressure testing

- plugins/modbus/modbus_tcp.c
- src/adapter/adapter.c
1. Fix neu_adapter_destroy memory leak
2. Fix neu_adapter_destroy memory leak
> Fix memory leak

- tools/config-syslog.sh
The tool config-syslog.py only supports rsyslog in linux platforms.
> Add tool config-syslog.py

- docs/json-api/neu_json_log.json
- include/json/neu_json_log.h
- plugins/restful/log_handle.c
- src/parser/neu_json_log.c
1. Add cache for log handler
2. Update restful log api to return page count
> Update restful log api to return page count

- docs/json-api/neu_json_license.json
- include/json/neu_json_license.h
- plugins/restful/handle.c
- plugins/restful/license.c
- plugins/restful/license.h
- plugins/restful/license_handle.c
- plugins/restful/license_handle.h
- src/parser/neu_json_license.c
1. Implement get license handler
2. Add get license restful endpoint
> Get license api

- plugins/mqtt/plugin_mqtt.c
- src/connection/mqtt_c_client.c
> [#320]Fixed crash when modifying mqtt settings

- plugins/mqtt/command/tty.c
> [#339]Fixed crash when calling ttys via mqtt

- include/neu_adapter.h
- src/adapter/adapter.c
- src/persist/persist.c
- src/persist/persist.h
> Fix node update persistence

- ft/persistence_test.robot
- plugins/mqtt/util.c
- tests/mqtt_test.cc
> Fix memory corruption under armv7l

- docs/json-persistence/json_adapter.json
- src/adapter/adapter.c
- src/core/neu_manager.c
- src/persist/json/persist_json_adapter.c
- src/persist/json/persist_json_adapter.h
- tests/json_persistence_test.cc
- tests/persistence_test.cc
> Add persistence with adapter id

- plugins/mqtt/mqtt.c
- Reduce the frequency of business trips when switching brokers
> Fix publish stop caused by write timeout

- CMakeLists.txt
- src/argparse.h
- src/daemon.c
- src/daemon.h
- src/main.c
Now running `neuron -d` will make neuron run as a daemon process.
> Add daemon mode

- plugins/ekuiper/CMakeLists.txt
- plugins/ekuiper/json_rw.c
- plugins/ekuiper/json_rw.h
- plugins/ekuiper/plugin_ekuiper.c
- plugins/ekuiper/plugin_ekuiper.h
- plugins/ekuiper/read_write.c
- plugins/ekuiper/read_write.h
This implementation use `nng_sendmsg` which is not as efficient as using nng_aio
> Update ekuiper plugin to forward trans data

- ft/api_http.resource
- ft/api_mqtt.resource
- ft/node_api_test.robot
- include/neuron/adapter_msg.h
- include/neuron/plugin.h
- plugins/mqtt/command/command.c
- plugins/mqtt/command/node.c
- plugins/mqtt/command/node.h
- plugins/restful/adapter_handle.c
- plugins/restful/adapter_handle.h
- plugins/restful/handle.c
- src/adapter/adapter.c
- src/adapter/adapter_info.h
- src/adapter/adapter_internal.h
- src/adapter/driver/driver.c
- src/base/neu_plugin_common.c
- src/core/message.h
- src/core/neu_manager.c
- src/core/neu_manager.h
> refactor adapter

- plugins/restful/datatag_handle.c
> fix(restful): handle_get_tags to filter group name correctly

- src/adapter/adapter.c
- src/core/neu_manager.c
- src/core/neu_manager.h
- src/persist/json/persist_json_adapter.c
- src/persist/json/persist_json_adapter.h
- src/persist/persist.c
- src/persist/persist.h
- tests/persistence_test.cc
Previously persistence data loading will stop at first error,
now updated to load as much data as possible ignoring errors.
Close #491
> fix(persist): load as much data as possible ignoring error

- plugins/restful/datatag_handle.c
- plugins/restful/http.c
- plugins/restful/http.h
- tests/http_test.cc
> Fix get tags restful api

- plugins/restful/datatag_handle.c
- src/base/neu_plugin_common.c
> Fix neu_system_find_group_config to compare group name correctly

- CMakeLists.txt
- include/neuron/type.h
- include/neuron/utils/async_queue.h
- include/neuron/utils/utextend.h
- src/adapter/driver/driver.c
- src/utils/async_queue.c
async queue used for FIFO processing asynchronous req and res
> async queue & fix bug

- ft/normal_test.robot
- ft/resource/api.resource
- plugins/restful/normal_handle.c
This reverts commit b16df3d3d3e9d67dcdff2132d650fcd574d516c2.
> Revert "change default password"

- .github/workflows/test-helm.yaml
Signed-off-by: bin <brian.xb.bian@gmail.com>
> ci: remove inputs and update check

- plugins/mqtt/mqtt_plugin.c
> fix(mqtt): crash caused by global static variables(v2.1.0)

- .github/workflows/check.yml
- src/adapter/adapter.c
This reverts commit ceda938e4e064c5d4fe549f847c4c5fbe5f0b9ad.
> Revert "qh test"

- .github/workflows/check.yml
- src/adapter/adapter.c
This reverts commit e997cffc8409805501ed69fd6370c61ead0eaee0.
> Revert "build for qh"

- CMakeLists.txt
This reverts commit dea4975a2267567364122e9aeabda1eeef569c42.
> Revert "link shared openssl"

- deploy/charts/neuron/Chart.yaml
- deploy/charts/neuron/README.md
- deploy/charts/neuron/templates/deployment.yaml
- deploy/charts/neuron/templates/pvc.yaml
- deploy/charts/neuron/values.yaml
Signed-off-by: bin <brian.xb.bian@gmail.com>
> support create pvc automatically

- src/connection/mqtt_client.c
1. use nng_send_aio instead of nng_sendmsg to avoid blocking due to NanoSDK quirks
2. add task queue for both sending/receiving messages
> fix(mqtt-client): add task queue and avoid blocking

- .gitmodules
- CMakeLists.txt
- README-CN.md
- README.md
> Make source self contained by removing uthash submodule

- src/adapter/adapter.c
fix:memory leak on adapter reply
> fix:memory leak on adapter reply

- plugins/mqtt/mqtt_handle.c
When received subscription without parameters, then upload data to
default topic `/neuron/${app}/${driver}/${group}`. This change is for
compatibility with neuron below 2.4.0.
> fix(mqtt): upload to default topic when no subscription parameter

- include/neuron/connection/mqtt_client.h
- include/neuron/utils/time.h
- plugins/mqtt/mqtt.json
- plugins/mqtt/mqtt_config.c
- plugins/mqtt/mqtt_config.h
- plugins/mqtt/mqtt_handle.c
- plugins/mqtt/mqtt_plugin.c
- plugins/mqtt/mqtt_plugin.h
- src/connection/mqtt_client.c
> feat(mqtt): add write request/response topic parameters

- persistence/0041_2.5.0_modbus_tmode.sql
- plugins/modbus/modbus_qh_tcp.c
- plugins/modbus/modbus_rtu.c
- plugins/modbus/modbus_stack.c
- plugins/modbus/modbus_tcp.c
> Backward compatibility with Modbus plugin for versions prior to 2.5.

- src/event/event_linux.c
This reverts commit 96f98d15b9cb506cf1de12a394c74916f075705d.
> Revert "chore(event): exit if error occurs"

- src/base/group.c
Fixes: https://emqx.atlassian.net/browse/NEURON-2330
> [v2.4]fix tags with write-only attribute will send read commands

- src/base/group.c
Fixes: https://emqx.atlassian.net/browse/NEURON-2330
> fix tags with write-only attribute will send read commands

- plugins/modbus/modbus.h
- plugins/modbus/modbus_req.c
- plugins/modbus/modbus_rtu.c
- plugins/modbus/modbus_stack.c
- plugins/modbus/modbus_stack.h
Enhancement: https://emqx.atlassian.net/browse/NEURON-2317
version: 2.5.3
> optimize modbus

- src/adapter/driver/driver.c
- src/adapter/driver/driver_internal.h
Enhancement: https://emqx.atlassian.net/browse/NEURON-2269
version: 2.5.3
> feat(driver): update and report immediately

- src/persist/persist.c
Fixes: https://emqx.atlassian.net/browse/NEURON-2391
> Pick to 2.4 fix: persist node_count and tag_count to signed number

- src/persist/persist.c
Fixes: https://emqx.atlassian.net/browse/NEURON-2391
> Pick to 2.5 fix: persist node_count and tag_count to signed number

- plugins/restful/plugin_handle.c
https://emqx.atlassian.net/browse/NEURON-2407
> prevent memory overflow in plugin_handle

- src/adapter/driver/cache.c
- src/adapter/driver/cache.h
- src/adapter/driver/driver.c
https://emqx.atlassian.net/browse/NEURON-2269
> fix(driver): cannot be uploaded in time when values have not changed

- plugins/modbus/modbus_stack.c
https://emqx.atlassian.net/jira/software/projects/NEURON/issues/NEURON-2316?jql=project%20%3D%20%22NEURON%22%20and%20assignee%20%3D%20currentUser%28%29%20ORDER%20BY%20created%20DESC
> reset response_size when retry

- tests/CMakeLists.txt
- tests/modbus_test.cc
https://emqx.atlassian.net/browse/NEURON-2318
> add modbus ut

- src/argparse.c
- src/argparse.h
- src/daemon.c
- src/daemon.h
- src/main.c
fix:close file fd
https://emqx.atlassian.net/browse/NEURON-2322
> feat:add cmd about stopping running neuron

- src/adapter/storage.c
- src/persist/persist.c
https://emqx.atlassian.net/browse/NEURON-2398
> Log optimization

- src/adapter/driver/driver.c
https://emqx.atlassian.net/browse/NEURON-2388
> fix(driver): memory leak

- src/adapter/adapter.c
https://emqx.atlassian.net/browse/NEURON-2361
> feat(metrics): reset metric values to zero when node stopped

- src/persist/persist.c
https://emqx.atlassian.net/browse/NEURON-2431
> fix node count of monitor

- src/adapter/adapter.c
https://emqx.atlassian.net/browse/NEURON-2361
> Pick to 2.5 feat(metrics): reset metric values to zero when node stopped

- ft/resource/api.resource
- ft/subscribe_test.robot
- include/neuron/adapter.h
- plugins/restful/group_config_handle.c
- plugins/restful/group_config_handle.h
- plugins/restful/handle.c
- src/adapter/adapter.c
- src/core/manager.c
- src/parser/neu_json_group_config.c
- src/parser/neu_json_group_config.h
https://emqx.atlassian.net/browse/NEURON-2314
> feat(restful): add api for subscribing multiple groups

- plugins/modbus/modbus_point.c
https://emqx.atlassian.net/browse/NEURON-2500
> correct modbus_read_max_byte

- ft/group_test.robot
- ft/resource/api.resource
- include/neuron/adapter.h
- include/neuron/persist/persist.h
- plugins/monitor/mqtt_handle.c
- plugins/restful/group_config_handle.c
- src/adapter/adapter.c
- src/adapter/adapter_internal.h
- src/adapter/driver/driver.c
- src/adapter/driver/driver_internal.h
- src/adapter/storage.c
- src/adapter/storage.h
- src/base/group.c
- src/base/group.h
- src/core/manager.c
- src/core/manager_internal.c
- src/core/manager_internal.h
- src/core/subscribe.c
- src/core/subscribe.h
- src/parser/neu_json_group_config.c
- src/parser/neu_json_group_config.h
- src/persist/persist.c
https://emqx.atlassian.net/browse/NEURON-2451
> feat(restful): group update api supports renaming group

- src/adapter/driver/driver.c
https://emqx.atlassian.net/browse/NEURON-2382
> fix(core): heap use after free

- include/neuron/connection/mqtt_client.h
- plugins/mqtt/mqtt.json
- plugins/mqtt/mqtt_config.c
- plugins/mqtt/mqtt_config.h
- plugins/mqtt/mqtt_plugin.c
- src/connection/mqtt_client.c
https://emqx.atlassian.net/browse/NEURON-1970
> feat(mqtt): add cache-sync-interval setting

- plugins/mqtt/mqtt.json
https://emqx.atlassian.net/browse/NEURON-1970
> fix(mqtt): cache-sync-interval setting default to 100

- src/base/metrics.c
https://emqx.atlassian.net/browse/NEURON-2421
> fix(metrics): use neuron process rss instead of system used memory

- include/neuron/plugin.h
- plugins/ekuiper/plugin_ekuiper.c
- plugins/modbus/modbus_rtu.c
- plugins/modbus/modbus_tcp.c
- plugins/monitor/monitor.c
- plugins/mqtt/mqtt_plugin.c
- plugins/restful/rest.c
- src/adapter/adapter.c
- src/adapter/adapter_internal.h
- src/adapter/driver/driver.c
- src/adapter/driver/driver_internal.h
- src/adapter/storage.c
- src/core/manager.c
- src/core/manager_internal.c
- src/core/manager_internal.h
- src/core/storage.c
https://emqx.atlassian.net/jira/software/projects/NEURON/boards/26/backlog?assignee=6077e60e9361560068ea4234&selectedIssue=NEURON-2458
https://emqx.atlassian.net/jira/software/projects/NEURON/boards/26/backlog?assignee=6077e60e9361560068ea4234&selectedIssue=NEURON-2460
https://emqx.atlassian.net/jira/software/projects/NEURON/boards/26/backlog?assignee=6077e60e9361560068ea4234&selectedIssue=NEURON-2424
> check license when add node/tag

- src/connection/mqtt_client.c
https://emqx.atlassian.net/jira/software/projects/NEURON/boards/26/backlog?assignee=6136b24eb38743006ae6f8b8&selectedIssue=NEURON-2540
> Pick to v2.5 fix(mqtt): SSL check server name

- src/connection/mqtt_client.c
https://emqx.atlassian.net/jira/software/projects/NEURON/boards/26/backlog?assignee=6136b24eb38743006ae6f8b8&selectedIssue=NEURON-2540
> fix(mqtt): SSL check server name

- src/core/manager_internal.c
https://emqx.atlassian.net/browse/NEURON-2462
> fix(template): add/validate tags in template instantiation

- plugins/mqtt/mqtt_config.c
- plugins/mqtt/mqtt_plugin.c
https://emqx.atlassian.net/browse/NEURON-1970
> fix(mqtt): `cache-sync-interval` setting default to 100 when cache disabled

- ft/group_test.robot
- src/adapter/driver/driver.c
- src/parser/neu_json_group_config.c
https://emqx.atlassian.net/browse/NEURON-2451
> fix(restful): update group name check for name confliction

- include/neuron/type.h
- plugins/ekuiper/json_rw.c
- plugins/ekuiper/plugin_ekuiper.c
- plugins/mqtt/mqtt_handle.c
- plugins/mqtt/mqtt_plugin.c
- plugins/restful/rw_handle.c
- src/adapter/driver/cache.c
- src/adapter/driver/driver.c
- src/connection/mqtt_client.c
- src/core/manager.c
https://emqx.atlassian.net/browse/NEURON-2499
> core: neu_type_ptr

- src/argparse.c
- src/daemon.c
- src/main.c
https://emqx.atlassian.net/jira/software/projects/NEURON/boards/26/backlog?assignee=63fd6325896d10ebd4704c06&selectedIssue=NEURON-2527
> feat:waiting exit when using stop cmd

- include/neuron/metrics.h
- src/adapter/driver/driver.c
https://emqx.atlassian.net/browse/NEURON-2518
> feat: add metrics for last group data acquisition error

- CMakeLists.txt
- include/neuron/utils/log.h
- src/adapter/adapter.c
- src/utils/log.c
https://emqx.atlassian.net/jira/software/projects/NEURON/boards/26?assignee=63fd6325896d10ebd4704c06&selectedIssue=NEURON-2538
> feat:rm log files when node delete or rename

- ft/resource/api.resource
- ft/template.robot
- include/neuron/adapter.h
- plugins/restful/handle.c
- plugins/restful/template_handle.c
- plugins/restful/template_handle.h
- src/adapter/adapter.c
- src/core/manager.c
- src/core/manager_internal.c
- src/core/manager_internal.h
- src/parser/neu_json_template.c
- src/parser/neu_json_template.h
https://emqx.atlassian.net/browse/NEURON-2461
> feat(restful): add template batch instantiation api

- src/argparse.c
https://emqx.atlassian.net/jira/software/projects/NEURON/boards/26/backlog?assignee=63fd6325896d10ebd4704c06&selectedIssue=NEURON-2569
> fixbug:check env and config file setting

- plugins/mqtt/mqtt.json
- plugins/mqtt/mqtt_config.c
- plugins/mqtt/mqtt_config.h
https://emqx.atlassian.net/browse/NEURON-2465
> feat(mqtt): remove `keypass` setting

- include/neuron/metrics.h
- src/adapter/adapter.c
- src/adapter/driver/driver.c
https://emqx.atlassian.net/browse/NEURON-2575
> feat: add metrics `tags_total`

- src/adapter/driver/driver.c
https://emqx.atlassian.net/browse/NEURON-2588
> fix: check tags is null

- plugins/monitor/monitor.json
- plugins/mqtt/mqtt.json
https://emqx.atlassian.net/browse/NEURON-2476
> chore: monitor and mqtt schema `client-id` use random str

- plugins/ekuiper/plugin_ekuiper.c
- plugins/monitor/monitor.json
- plugins/mqtt/mqtt.json
- plugins/mqtt/mqtt_handle.c
- plugins/mqtt/mqtt_handle.h
- plugins/mqtt/mqtt_plugin.c
- plugins/mqtt/mqtt_plugin.h
- src/adapter/adapter.c
- src/core/manager.c
https://emqx.atlassian.net/browse/NEURON-2589
> fix(mqtt): handle driver name update

- include/neuron/adapter.h
- plugins/ekuiper/plugin_ekuiper.c
- plugins/mqtt/mqtt_handle.c
- plugins/mqtt/mqtt_handle.h
- plugins/mqtt/mqtt_plugin.c
- plugins/mqtt/mqtt_plugin.h
- src/adapter/adapter.c
- src/core/manager.c
https://emqx.atlassian.net/browse/NEURON-2594
> fix(mqtt): handle group update

- src/connection/connection.c
https://emqx.atlassian.net/browse/NEURON-2596
> connection: recv all msg

- src/core/manager.c
https://emqx.atlassian.net/browse/NEURON-2499
> fix(core): trans data dup

- src/adapter/driver/driver.c
https://emqx.atlassian.net/jira/software/projects/NEURON/boards/26?assignee=63fd6325896d10ebd4704c06&selectedIssue=NEURON-2614
> fixbug:index error when endian in BL or LB

- src/adapter/driver/driver.c
https://emqx.atlassian.net/jira/software/projects/NEURON/boards/26?assignee=63fd6325896d10ebd4704c06&selectedIssue=NEURON-2614
> [v2.6]fixbug:index error when endian in BL or LB

- src/utils/log.c
https://emqx.atlassian.net/jira/software/projects/NEURON/boards/26?assignee=63fd6325896d10ebd4704c06&selectedIssue=NEURON-2615
> [v2.6]fixbug:log file name filtering error

- src/utils/log.c
https://emqx.atlassian.net/jira/software/projects/NEURON/boards/26?assignee=63fd6325896d10ebd4704c06&selectedIssue=NEURON-2615
> fixbug:log file name filtering error

- src/daemon.c
https://emqx.atlassian.net/browse/NEURON-2620
> [v2.6]fixbug:send sigkill when stop timeout

- src/adapter/driver/driver.c
https://emqx.atlassian.net/browse/NEURON-2613
> Pick to v2.6 fix(core): trigger group change when updating group name

- src/daemon.c
https://emqx.atlassian.net/browse/NEURON-2620
> fixbug:send sigkill when stop timeout

- src/adapter/driver/driver.c
https://emqx.atlassian.net/browse/NEURON-2619
> Pick to v2.6 fix(metrics): update NEU_METRIC_TAGS_TOTAL when deleting group

- include/neuron/define.h
- include/neuron/plugin.h
- src/adapter/adapter.c
- src/adapter/adapter_internal.h
- src/adapter/driver/driver.c
https://emqx.atlassian.net/jira/software/projects/NEURON/boards/26?assignee=63fd6325896d10ebd4704c06&selectedIssue=NEURON-2618
> feat:add tag cache type

- ft/resource/api.resource
- ft/template.robot
- include/neuron/adapter.h
- include/neuron/persist/persist.h
- plugins/restful/template_handle.c
- src/adapter/storage.c
- src/base/template.c
- src/base/template.h
- src/core/manager.c
- src/core/manager_internal.c
- src/core/storage.c
- src/core/storage.h
- src/parser/neu_json_template.c
- src/parser/neu_json_template.h
- src/persist/persist.c
https://emqx.atlassian.net/browse/NEURON-2624
> feat(restful): support update template group name

- ft/resource/api.resource
- ft/template.robot
- include/neuron/adapter.h
- include/neuron/persist/persist.h
- plugins/restful/template_handle.c
- src/adapter/storage.c
- src/base/template.c
- src/base/template.h
- src/core/manager.c
- src/core/manager_internal.c
- src/core/storage.c
- src/core/storage.h
- src/parser/neu_json_template.c
- src/parser/neu_json_template.h
- src/persist/persist.c
https://emqx.atlassian.net/browse/NEURON-2624
> Pick to v2.6 feat(restful): support update template group name

- include/neuron/define.h
- src/main.c
https://emqx.atlassian.net/browse/NEURON-2628
> fixbug:buffer size too small,host:port be truncated

- src/connection/mqtt_client.c
https://emqx.atlassian.net/browse/NEURON-2625
> fix(mqtt): enable SNI only when configured host is not IP address

- src/connection/mqtt_client.c
https://emqx.atlassian.net/browse/NEURON-2625
> Pick to v2.6 fix(mqtt): enable SNI only when configured host is not IP address

- persistence/0050_2.6.0_virtual_license.sql
https://emqx.atlassian.net/browse/NEURON-2600
> feat: add virtual license sql schema

- persistence/0050_2.6.0_virtual_license.sql
https://emqx.atlassian.net/browse/NEURON-2600
> Pick to v2.6 feat: add virtual license sql schema

- src/adapter/driver/driver.c
https://emqx.atlassian.net/browse/NEURON-2638
> fix(driver): check tags size

- src/adapter/driver/driver.c
https://emqx.atlassian.net/jira/software/projects/NEURON/boards/26?assignee=63fd6325896d10ebd4704c06&selectedIssue=NEURON-2614
> [v2.5]fixbug:index error when endian in BL or LB

- plugins/mqtt/mqtt_plugin.h
- src/core/subscribe.c
https://emqx.atlassian.net/browse/NEURON-2642
> Pick to v2.6 fix: zero out trailing hash key string

- plugins/mqtt/mqtt_plugin.h
- src/core/subscribe.c
https://emqx.atlassian.net/browse/NEURON-2642
> fix: zero out trailing hash key string

- plugins/modbus/modbus_req.c
https://emqx.atlassian.net/browse/NEURON-2658
> fix(modbus):rtu server recv&send

- ft/modbus_rtu_test.robot
- ft/resource/simulator.resource
- include/neuron/connection/neu_connection.h
- plugins/modbus/modbus-rtu.json
- plugins/modbus/modbus-tcp.json
- plugins/modbus/modbus_tcp.c
- simulator/modbus_simulator.c
- src/connection/connection.c
https://emqx.atlassian.net/browse/NEURON-2601
> core&modbus support ipv6

- plugins/restful/log_handle.c
- src/adapter/adapter.c
- src/core/manager.c
- src/parser/neu_json_log.c
- src/parser/neu_json_log.h
https://emqx.atlassian.net/browse/NEURON-2609
> Switch the log level and no longer automatically switch back

- src/adapter/adapter.c
- src/core/manager.c
This reverts commit b7bafef1e0856bff7dcaabb26a7048a6be8aab48.
> Revert "adapter/manager recv list timeout"

- dev.conf
- neuron.json
- src/argparse.c
- src/argparse.h
- src/main.c
- zlog.conf
https://emqx.atlassian.net/browse/NEURON-2664
> feat: support logs to remote syslog server

- dev.conf
- neuron.json
- src/argparse.c
- src/argparse.h
- src/main.c
- zlog.conf
https://emqx.atlassian.net/browse/NEURON-2664
> Pick to v2.6 feat: support logs to remote syslog server 

- dev.conf
- zlog.conf
https://emqx.atlassian.net/browse/NEURON-2664
> fix: syslog format

- plugins/modbus/modbus_point.c
- plugins/modbus/modbus_req.c
https://emqx.atlassian.net/browse/NEURON-2637
> verify that the length of modbus bytes point is even

- tests/ft/neuron/api.py
https://emqx.atlassian.net/browse/NEURON-2694
> test: augment ft neuron api

- tests/ft/neuron/common.py
https://emqx.atlassian.net/browse/NEURON-2694
> test: ft description support printing test arguments

- tests/ft/neuron/common.py
- tests/ft/neuron/process.py
https://emqx.atlassian.net/browse/NEURON-2694
> test: ft api support restart neuron process

- tests/ft/neuron/api.py
https://emqx.atlassian.net/browse/NEURON-2694
> test: ft add template api

- tests/ft/neuron/api.py
https://emqx.atlassian.net/browse/NEURON-2695
> test: ft add virtual license api

- src/adapter/driver/driver.c
This reverts commit cfa8b4d54391934743231ecd0250e5a046a682ff.
> Revert "debug: write performance"

- tests/ft/neuron/api.py
https://emqx.atlassian.net/browse/NEURON-2723
> test: add ft get hardware token api

- src/connection/connection.c
This reverts commit b73a1cefc3c3fc6519876de3712e6817030b54d8.
> Revert "debug delay 100ms"

- include/neuron/msg.h
- plugins/ekuiper/read_write.c
- plugins/mqtt/mqtt_handle.c
- plugins/restful/rw_handle.c
- src/adapter/adapter.c
- src/adapter/driver/driver.c
- src/core/manager.c
- src/parser/neu_json_rw.c
https://emqx.atlassian.net/browse/NEURON-2738
> refactor: reduce message size

- src/daemon.c
https://emqx.atlassian.net/browse/NEURON-2766
> fix: pid file work around fs.protected_regular

- src/daemon.c
https://emqx.atlassian.net/browse/NEURON-2766
> Pick to v2.6 fix: pid file work around fs.protected_regular

- dev.conf
- src/main.c
- zlog.conf
https://emqx.atlassian.net/browse/NEURON-2803
> feat: syslog message add priority

- dev.conf
- src/main.c
- zlog.conf
https://emqx.atlassian.net/browse/NEURON-2803
> Pick to v2.6 feat: syslog message add priority

- src/core/manager_internal.c
https://emqx.atlassian.net/browse/NEURON-2738
> fix: memory used after free

- include/neuron/metrics.h
- plugins/restful/metric_handle.c
- src/base/metrics.c
https://emqx.atlassian.net/browse/NEURON-2762
> feat: add license tag metrics

- dev.conf
- zlog.conf
https://emqx.atlassian.net/browse/NEURON-2818
> feat(syslog): new log format

- plugins/restful/rw_handle.c
- src/adapter/driver/driver.c
> Revert "[v2.6]fix: write tags api int->double type"

- plugins/mqtt/mqtt_handle.c
- tests/ft/app/test_mqtt.py
https://emqx.atlassian.net/browse/NEURON-2649
> test(mqtt): add mqtt write tags ft

- plugins/restful/rw_handle.c
- src/adapter/driver/driver.c
https://github.com/emqx/neuron/pull/1713
> [main]fix: write tags api int->double type

- src/connection/connection.c
This reverts commit 1151bb43b8f47209156a3b065acf15a540b03c4c.
> Revert "fix(conn): lock conn buf"

- .github/workflows/check.yml
- create_cov_report.sh
- plugins/ekuiper/json_rw.c
- plugins/ekuiper/plugin_ekuiper.c
- tests/ft/app/test_ekuiper.py
- tests/ft/neuron/common.py
https://emqx.atlassian.net/browse/NEURON-2692
> test(ekuiper): add ft

- include/neuron/json/neu_json_rw.h
- include/neuron/msg.h
- plugins/restful/rw_handle.c
- src/adapter/driver/driver.c
- src/base/group.c
- src/base/group.h
- src/base/msg_internal.h
- src/parser/neu_json_rw.c
- tests/ft/driver/test_modbus.py
- tests/ft/neuron/api.py
https://emqx.atlassian.net/browse/NEURON-2875
> Pick to v2.7 feat(core): read group support filter

- include/neuron/json/neu_json_rw.h
- include/neuron/msg.h
- plugins/restful/rw_handle.c
- src/adapter/driver/driver.c
- src/base/group.c
- src/base/group.h
- src/base/msg_internal.h
- src/parser/neu_json_rw.c
- tests/ft/driver/test_modbus.py
- tests/ft/neuron/api.py
https://emqx.atlassian.net/browse/NEURON-2875
> feat(core): read group support filter

- include/neuron/msg.h
- plugins/restful/group_config_handle.c
- src/core/manager.c
- src/core/manager_internal.c
- src/core/manager_internal.h
- src/core/subscribe.c
- src/core/subscribe.h
- tests/ft/http_api/test_http_api.py
- tests/ft/neuron/api.py
https://emqx.atlassian.net/browse/NEURON-2876
> Pick to v2.7 feat(core): get subscribe group request support filter

- include/neuron/msg.h
- plugins/restful/group_config_handle.c
- src/core/manager.c
- src/core/manager_internal.c
- src/core/manager_internal.h
- src/core/subscribe.c
- src/core/subscribe.h
- tests/ft/http_api/test_http_api.py
- tests/ft/neuron/api.py
https://emqx.atlassian.net/browse/NEURON-2876
> feat(core): get subscribe group request support filter

- CMakeLists.txt
- include/neuron/persist/persist.h
- src/persist/persist.c
- src/persist/persist_impl.h
- src/persist/sqlite.c
- src/persist/sqlite.h
https://emqx.atlassian.net/browse/NEURON-2686
> feat(persist): abstract sqlite persister implementation

- include/neuron/msg.h
- plugins/restful/adapter_handle.c
- src/core/manager.c
- src/core/manager_internal.c
- src/core/manager_internal.h
- src/core/storage.c
- src/parser/neu_json_node.c
- src/parser/neu_json_node.h
- tests/ft/app/test_app.py
- tests/ft/driver/test_driver.py
- tests/ft/neuron/api.py
https://emqx.atlassian.net/browse/NEURON-2874
> feat(restful): add node api support setting

- include/neuron/utils/set.h
- plugins/restful/adapter_handle.c
- plugins/restful/global_config_handle.c
- plugins/restful/global_config_handle.h
- plugins/restful/handle.c
- src/parser/neu_json_global_config.c
- src/parser/neu_json_global_config.h
- src/parser/neu_json_node.c
- src/parser/neu_json_tag.c
- src/parser/neu_json_tag.h
- tests/ft/http_api/test_http_api.py
- tests/ft/neuron/api.py
https://emqx.atlassian.net/browse/NEURON-2873
> feat(restful): add GET drivers api

- src/persist/sqlite.c
> fix(persit): neu_sqlite_persister_create free non-malloc memory

- CMakeLists.txt
https://emqx.atlassian.net/browse/NEURON-2928
> build: cmake link libatomic

- include/neuron/metrics.h
- include/neuron/plugin.h
- include/neuron/utils/rolling_counter.h
- plugins/mqtt/mqtt_handle.c
- plugins/mqtt/mqtt_plugin.c
- src/adapter/adapter.c
- src/base/metrics.c
- tests/ft/metrics/test_metrics.py
- tests/ut/CMakeLists.txt
- tests/ut/rolling_counter_test.cc
https://emqx.atlassian.net/browse/NEURON-2926
> feat(mqtt): add rolling metrics

- include/neuron/metrics.h
- include/neuron/plugin.h
- include/neuron/utils/rolling_counter.h
- plugins/mqtt/mqtt_handle.c
- plugins/mqtt/mqtt_plugin.c
- src/adapter/adapter.c
- src/base/metrics.c
- tests/ft/metrics/test_metrics.py
- tests/ut/CMakeLists.txt
- tests/ut/rolling_counter_test.cc
https://emqx.atlassian.net/browse/NEURON-2926
> Pick to v2.7 feat(mqtt): add rolling metrics

- plugins/ekuiper/plugin_ekuiper.c
- plugins/ekuiper/read_write.c
- src/base/metrics.c
- src/core/manager_internal.c
https://emqx.atlassian.net/browse/NEURON-2927
> feat(ekuiper): add rolling metrics

- include/neuron/metrics.h
- include/neuron/utils/rolling_counter.h
- plugins/ekuiper/plugin_ekuiper.c
- plugins/ekuiper/read_write.c
- plugins/restful/metric_handle.c
- src/adapter/adapter.c
https://emqx.atlassian.net/browse/NEURON-2927
> Pick to v2.7: feat(ekuiper): add rolling metrics

- include/neuron/adapter.h
- src/adapter/adapter.c
- src/adapter/driver/driver.c
- src/base/msg_internal.h
- src/core/manager.c
- src/core/manager_internal.c
- src/core/manager_internal.h
- src/core/node_manager.c
- src/core/node_manager.h
- src/core/subscribe.c
- src/core/subscribe.h
https://emqx.atlassian.net/browse/NEURON-2930
> feat: use abstract domain socket instead of UDP

- README.md
> correct links in README

- src/adapter/adapter.c
- src/core/manager.c
https://emqx.atlassian.net/browse/NEURON-3029
> feat(core): set domain socket to block mode and 1s timeout

- src/adapter/adapter.c
- src/core/manager.c
https://emqx.atlassian.net/browse/NEURON-3029
> Pick to v2.8 feat(core): set domain socket to block mode and 1s timeout

- src/adapter/adapter.c
This reverts commit 59987563df954d804732cfa0b41d93b28bab8b22.
> Revert "fd timeout 3s"

- src/adapter/adapter.c
- tests/ft/tag/test_tag.py
https://emqx.atlassian.net/browse/NEURON-3035
> Pick to v2.8 fix(core): persist group when adding gtags

- src/adapter/adapter.c
- tests/ft/tag/test_tag.py
https://emqx.atlassian.net/browse/NEURON-3035
> fix(core): persist group when adding gtags

- src/core/manager_internal.c
https://emqx.atlassian.net/browse/NEURON-3039
> fix(core): eliminate NEU_REQ_ADD_DRIVERS request data race

- include/neuron/msg.h
- include/neuron/type.h
- persistence/0070_2.7.5_tag_time_type.sql
- src/adapter/driver/cache.c
- src/adapter/driver/driver.c
- src/base/tag.c
- src/parser/neu_json_rw.c
- src/parser/neu_json_tag.c
https://emqx.atlassian.net/browse/NEURON-3050
> Pick to v2.7 feat(core): add NEU_TYPE_TIME and NEU_TYPE_DATA_AND_TIME

- include/neuron/msg.h
- include/neuron/type.h
- persistence/0070_2.7.5_tag_time_type.sql
- src/adapter/driver/cache.c
- src/adapter/driver/driver.c
- src/base/tag.c
- src/parser/neu_json_rw.c
- src/parser/neu_json_tag.c
https://emqx.atlassian.net/browse/NEURON-3050
> feat(core): add NEU_TYPE_TIME and NEU_TYPE_DATA_AND_TIME

- include/neuron/type.h
- src/base/tag.c
https://emqx.atlassian.net/browse/NEURON-3050
> fix(core): remove NEU_TYPE_TIME and NEU_TYPE_DATA_AND_TIME option

- include/neuron/msg.h
- include/neuron/type.h
- persistence/0070_2.7.5_tag_time_type.sql
- src/adapter/driver/cache.c
- src/adapter/driver/driver.c
- src/base/tag.c
- src/parser/neu_json_rw.c
- src/parser/neu_json_tag.c
https://emqx.atlassian.net/browse/NEURON-3050
> Pick to v2.8 feat(core): add NEU_TYPE_TIME and NEU_TYPE_DATA_AND_TIME

- plugins/ekuiper/json_rw.c
- plugins/ekuiper/plugin_ekuiper.c
- plugins/ekuiper/plugin_ekuiper.h
- plugins/ekuiper/read_write.c
https://emqx.atlassian.net/browse/NEURON-3060
> Pick to v2.6 fix(ekuiper): memory leak and data race

- plugins/ekuiper/json_rw.c
- plugins/ekuiper/plugin_ekuiper.c
- plugins/ekuiper/plugin_ekuiper.h
- plugins/ekuiper/read_write.c
https://emqx.atlassian.net/browse/NEURON-3060
> Pick to v2.7: fix(ekuiper): memory leak and data race

- plugins/ekuiper/plugin_ekuiper.c
- plugins/ekuiper/plugin_ekuiper.h
- plugins/ekuiper/read_write.c
https://emqx.atlassian.net/browse/NEURON-3060
> Pick to v2.8 fix(ekuiper): check received aio data race

- plugins/ekuiper/plugin_ekuiper.c
- plugins/ekuiper/plugin_ekuiper.h
- plugins/ekuiper/read_write.c
https://emqx.atlassian.net/browse/NEURON-3060
> fix(ekuiper): check received aio NULL msg

- plugins/ekuiper/json_rw.c
- plugins/ekuiper/json_rw.h
- plugins/ekuiper/read_write.c
- plugins/ekuiper/read_write.h
- tests/ft/app/test_ekuiper.py
https://emqx.atlassian.net/browse/NEURON-3061
> feat(ekuiper): support write multiple tags

- src/parser/neu_json_rw.c
https://emqx.atlassian.net/browse/NEURON-3075
> fix(restful): read api invalid free

- plugins/mqtt/CMakeLists.txt
- plugins/mqtt/aws-iot.json
- plugins/mqtt/aws_iot_plugin.c
- plugins/mqtt/mqtt_plugin_intf.c
- plugins/mqtt/mqtt_plugin_intf.h
https://emqx.atlassian.net/browse/NEURON-3008
> feat(aws-iot): add aws-iot plugin

- include/neuron/metrics.h
- plugins/restful/metric_handle.c
- src/adapter/adapter.c
- src/adapter/adapter_internal.h
- src/adapter/driver/driver.c
https://emqx.atlassian.net/browse/NEURON-3101
> fix: reset metrics when node stopped

- include/neuron/metrics.h
- plugins/restful/metric_handle.c
- src/adapter/adapter.c
- src/adapter/adapter_internal.h
- src/adapter/driver/driver.c
https://emqx.atlassian.net/browse/NEURON-3101
> Pick to v2.7: fix: reset metrics when node stopped

- default_plugins.json
- plugins/mqtt/CMakeLists.txt
- plugins/mqtt/azure-iot.json
- plugins/mqtt/azure_iot_plugin.c
- plugins/mqtt/mqtt_config.c
- plugins/mqtt/mqtt_config.h
- plugins/mqtt/mqtt_handle.c
- plugins/mqtt/mqtt_handle.h
- plugins/mqtt/mqtt_plugin.h
- plugins/mqtt/mqtt_plugin_intf.c
- plugins/mqtt/mqtt_plugin_intf.h
https://emqx.atlassian.net/browse/NEURON-3082
> feat: add Azure IoT plugin

- .github/workflows/check.yml
- create_cov_report.sh
- include/neuron/connection/mqtt_client.h
- plugins/mqtt/azure-iot.json
- plugins/mqtt/azure_iot_plugin.c
- plugins/mqtt/mqtt_config.c
- plugins/mqtt/mqtt_config.h
- src/connection/mqtt_client.c
- tests/ft/app/test_azure.py
- tests/ut/CMakeLists.txt
- tests/ut/mqtt_client_test.cc
https://emqx.atlassian.net/browse/NEURON-3082
> test(azure): add ft

- plugins/modbus/modbus.h
This reverts commit 3ad51811ff2e849f24d3af3dad4c0e39e25a6495.
> Revert "test"

- plugins/mqtt/mqtt.json
https://emqx.atlassian.net/browse/NEURON-3147
> feat(mqtt): schema client-id and write req/resp topic default value

- plugins/mqtt/mqtt.json
https://emqx.atlassian.net/browse/NEURON-3147
> Pick to v2.9 feat(mqtt): schema client-id and write req/resp topic default value

- include/neuron/plugin.h
- src/adapter/driver/driver.c
https://emqx.atlassian.net/browse/NEURON-3072
> feat(core): add `interval` field to struct neu_plugin_group

- include/neuron/plugin.h
- src/adapter/driver/driver.c
https://emqx.atlassian.net/browse/NEURON-3072
> Pick to v2.9 feat(core): add `interval` field to struct neu_plugin_group

- include/neuron/errcodes.h
https://emqx.atlassian.net/browse/NEURON-3191
> Pick to v2.8 chore: add error code `NEU_ERR_BODY_TOO_BIG`

- include/neuron/errcodes.h
https://emqx.atlassian.net/browse/NEURON-3191
> Pick to v2.9 chore: add error code `NEU_ERR_BODY_TOO_BIG`

- include/neuron/errcodes.h
https://emqx.atlassian.net/browse/NEURON-3191
> chore: add error code `NEU_ERR_BODY_TOO_BIG`

- src/adapter/driver/driver.c
This reverts commit 458af374bbd5f305bb9072bde002befad34e40b9.
> Revert "cyclic reporting does not detect change"

- plugins/restful/rw_handle.c
Resolves https://github.com/emqx/neuron/issues/2151
> fix:correction of field name length detection

- plugins/modbus/modbus-rtu.json
- plugins/modbus/modbus-tcp.json
- plugins/mqtt/aws-iot.json
- plugins/mqtt/mqtt.json
https://emqx.atlassian.net/browse/NEURON-3223
> chore: clean setting description

- include/neuron/connection/mqtt_client.h
- plugins/mqtt/mqtt_plugin_intf.c
- src/connection/mqtt_client.c
- src/core/manager.c
https://emqx.atlassian.net/browse/NEURON-3216
> Pick to v2.9 feat(mqtt): remove mqtt cache db when node deleted

- include/neuron/connection/mqtt_client.h
- plugins/mqtt/mqtt_plugin_intf.c
- src/connection/mqtt_client.c
- src/core/manager.c
https://emqx.atlassian.net/browse/NEURON-3216
> feat(mqtt): remove mqtt cache db when node deleted

- plugins/mqtt/azure_iot_plugin.c
- plugins/mqtt/mqtt_config.c
https://github.com/neugates/NanoSDK/pull/1/files
> MQTT default version v5

- include/neuron/msg.h
- plugins/restful/normal_handle.c
- plugins/restful/normal_handle.h
- plugins/restful/rest.c
- src/adapter/adapter.c
- src/base/msg_internal.h
- src/core/manager.c
- src/core/plugin_manager.c
- src/core/plugin_manager.h
- tests/ft/http_api/test_http_api.py
> check plugin schema exist

- src/main.c
> #2288: avoiding duplicate release resources

- CMakeLists.txt
- default_plugins.json
- plugins/file/CMakeLists.txt
- plugins/file/file.json
- plugins/file/file_plugin.c
This reverts commit 0e89e61d8cfe876d46b378f9c7db1c5de91a4ca2.
> Revert "rm file plugin"

- install_dependencies.sh
Script for automatically installing dependency libraries
> Script for automatically installing dependency libraries

- include/neuron/json/json.h
- include/neuron/msg.h
- src/adapter/driver/driver.c
- src/utils/json.c
This reverts commit c1e541ecb19faf9a177c91897b03ce8b1d2c828f.
> Revert "write int64/uint64 with string"

- .github/workflows/check.yml
- .github/workflows/ci.yml
2.optimize and reduce CI resource usage
> 1.update ci runner os version 2.optimize and reduce CI resource usage
